// Auto-generated by scripts/build-stat-dict.mjs — do not edit by hand.
// Re-exports from split generated files. Статы только по строковому id.

export { statNamesRuByStringIdGenerated } from "./statNamesByStringId.generated";
export { statNamesRuReducedByStringIdGenerated } from "./statNamesRuReducedByStringId.generated";
export { statStringToIdGenerated } from "./statStringToId.generated";
export { passiveNamesRuByIdGenerated } from "./passiveNamesById.generated";
export { passiveSkillGraphIdToNameRuGenerated } from "./passiveSkillGraphIdToNameRu.generated";
export { statIdByRuNameGenerated } from "./statIdByRuName.generated";
export { statTemplatesEnByStringIdGenerated } from "./statTemplatesEnByStringId.generated";

